config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :attachments, except: [:update, :edit, :new, :show]

  namespace :cms do
    resources :users, only:[:show, :index]
    resources :tags
    resources :articles do
      post :top
    end
    resources :comments, except: [:new, :show]
  end

  resources :notices, only: [:index, :create, :destroy]

  %w(info seo captcha adverts users about_us map).each do |a|
    get "site/#{a}"
    post "site/#{a}"
  end
  put 'site/role'
  get 'site/status'
  get 'site' => 'site#index'

  get 'ueditor' =>'ueditor#index'
  post 'ueditor' =>'ueditor#index'

  get 'personal/logs'

  resources :books, only: [:index, :show]

  get 'about_us' => 'home#about_us'
  get 'search' => 'home#search'
  get 'rss.atom' => 'home#rss', format: false, as: :rss
  get 'robots.txt' => 'home#robots', format: false, as: :robots
  get 'baidu_verify_(*id)', to: 'home#baidu', as: :baidu, format: true, constraints: {format: :html}
  get 'google(*id)', to: 'home#google', as: :google, format: true, constraints: {format: :html}

  namespace :questionnaire do
    resources :answers, only: [:destroy]
    resources :questions, except: [:index, :show]
    resources :reports do
      post :answer
      get :result
    end
  end

  resources :friend_links, only:[:index, :create, :destroy]
  resources :leave_words, only:[:index, :create, :destroy]
  get 'utils' =>'utils#index'

  devise_for :users

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'

end

app/models/questionnaire.rb
module Questionnaire
  def self.table_name_prefix
    'questionnaire_'
  end
end

app/models/questionnaire/answer.rb
class Questionnaire::Answer < ActiveRecord::Base

end

app/models/questionnaire/question.rb
class Questionnaire::Question < ActiveRecord::Base
  belongs_to :report
  validates :name, presence: true
  validates :flag, presence: true


  enum flag: [:single, :multi, :y_n]
end

app/models/questionnaire/report.rb
class Questionnaire::Report < ActiveRecord::Base
  validates :title, presence: true
  validates :summary, presence: true

  has_many :questions, class_name: 'Questionnaire::Question'
end

app/controllers/questionnaire/answers_controller.rb
class Questionnaire::AnswersController < ApplicationController
  before_action :must_be_admin!

  def destroy
    Questionnaire::Answer.destroy_all uid: params[:id]
    flash[:notice] = t 'messages.success'
    redirect_to questionnaire_report_result_path(params[:report_id])
  end
end

app/controllers/questionnaire/questions_controller.rb
class Questionnaire::QuestionsController < ApplicationController
  layout 'personal'

  def new
    @question = Questionnaire::Question.new report_id: params[:report_id]
  end

  def create
    r = Questionnaire::Question.new __params
    if r.save
      flash[:notice] = t 'messages.success'
      redirect_to edit_questionnaire_report_path(r.report)
    else
      flash[:alert] = r.errors.full_messages
      @report = r
      render 'new'
    end
  end


  def edit
    @question = Questionnaire::Question.find params[:id]
  end

  def update
    q = Questionnaire::Question.find params[:id]
    if q.update(__params)
      flash[:notice] = t 'messages.success'
      redirect_to edit_questionnaire_report_path(q.report)
    else
      flash[:alert] = q.errors.full_messages
      @report = q
      render 'edit'
    end

  end

  def destroy
    q = Questionnaire::Question.find params[:id]
    q.destroy
    flash[:notice] = t 'messages.success'
    redirect_to edit_questionnaire_report_url(q.report)
  end

  private
  def __params
    params.require(:questionnaire_question).permit :name, :flag, :args, :report_id
  end
end

app/controllers/questionnaire/reports_controller.rb
class Questionnaire::ReportsController < ApplicationController
  before_action :must_be_admin!, except: [:show, :answer]
  layout 'personal'

  def result
    @report = Questionnaire::Report.find params[:report_id]
    qus = @report.questions.select(:name, :id).order id: :asc
    @answers = Questionnaire::Answer.select(:uid).order(uid: :desc).distinct.map do |a|
      {
          id: a.uid,
          created_at: Questionnaire::Answer.where(uid: a.uid).first.created_at,
          args: qus.map { |q| "#{q.name}: #{Questionnaire::Answer.select(:content).where(uid: a.uid, question_id: q).first.content}" }
      }
    end
    render layout: 'cms'
  end

  def answer
    if recaptcha?
      uid = SecureRandom.uuid
      now = Time.now
      r = Questionnaire::Report.select(:id).find params[:report_id]
      r.questions.select(:id).each do |q|
        Questionnaire::Answer.create question_id: q.id, content: params["f_#{q.id}".to_sym], uid: uid, created_at: now
      end
      flash[:notice] = t 'messages.success'
    else
      flash[:alert] = t 'messages.failed'
    end
    redirect_to questionnaire_report_path(params[:report_id])
  end

  def index
    @reports = initialize_grid(Questionnaire::Report.select(:id, :title, :updated_at).order(id: :desc))
  end

  def new
    @report = Questionnaire::Report.new
  end

  def create
    r = Questionnaire::Report.new __params
    if r.save
      flash[:notice] = t 'messages.success'

      redirect_to questionnaire_reports_path
    else
      flash[:alert] = r.errors.full_messages
      @report = r
      render 'new'
    end
  end

  def show
    @report = Questionnaire::Report.find params[:id]
    render layout: 'cms'
  end

  def edit
    @report = Questionnaire::Report.find params[:id]
  end

  def update
    r = Questionnaire::Report.find params[:id]
    if r.update(__params)
      flash[:notice] = t 'messages.success'
      redirect_to questionnaire_reports_path
    else
      flash[:alert] = r.errors.full_messages
      @report = r
      render 'edit'
    end

  end

  def destroy
    Questionnaire::Report.destroy params[:id]
    flash[:notice] = t 'messages.success'
    redirect_to questionnaire_reports_path
  end

  private
  def __params
    params.require(:questionnaire_report).permit(:title, :summary)
  end
end

app/views/questionnaire/reports/edit.html.erb
<h3>
  <%= @title = t '.title', title: @report.title %>
  <%= link_to t('.add'), new_questionnaire_question_path(report_id: @report.id), class: 'btn btn-success btn-sm' %>
</h3>
<hr/>
<%= simple_form_for @report do |f| %>
    <%= f.input :title, autofocus: true %>
    <%= f.input :summary, as: :text %>
    <h4><%= t '.questions' %></h4>
    <hr/>

    <% @report.questions.each do |q| %>
        <blockquote class="blockquote">
          <p>
            <%= q.name %>
          </p>
          <footer>
            <%= render 'shared/button', title: :edit, href: edit_questionnaire_question_path(q), sm: true %>
            <%= render 'shared/button', title: :remove, href: questionnaire_question_path(q), sm: true %>
          </footer>
        </blockquote>
    <% end %>

    <%= f.button :submit, t('buttons.submit') %>
    <%= link_to t('buttons.back'), :back %>
<% end %>

app/views/questionnaire/reports/index.html.erb
<% @title = t '.title' %>
<p>
  <%= render 'shared/button', title: :new, href: new_questionnaire_report_path, sm: true %>
</p>
<%= grid(@reports) do |g|
  g.column name: t('table.columns.title') do |i|
    link_to i.title, questionnaire_report_path(i), target: '_blank'
  end
  g.column name: t('table.columns.updated_at') do |i|
    time_ago_in_words i.updated_at
  end
  g.column name: t('buttons.manage') do |i|
    render 'shared/button', title: :remove, href: questionnaire_report_path(i), sm: true
  end
end -%>

app/views/questionnaire/reports/new.html.erb
<%= simple_form_for @report do |f| %>
    <%= f.input :title, autofocus: true %>
    <%= f.input :summary, as: :text %>
    <%= f.button :submit, t('buttons.submit') %>
<% end %>

app/views/questionnaire/reports/result.html.erb
<div class="row">
  <div class="col-md-offset-1 col-md-10">

    <h3><%= @title = t '.title', title: @report.title %></h3>
    <hr/>
    <p>
      <%= raw to_html(@report.summary) %>
    </p>
    <% @answers.each do |a| %>
        <blockquote class="blockquote">
          <p>
            <%= raw a.fetch(:args).join('<br/>') %>
          </p>
          <footer>
            <% time_ago_in_words a.fetch(:created_at) %>
            <em>
              <%= render 'shared/button', title: :remove, sm: true, href: questionnaire_answer_path(a.fetch(:id), report_id: @report.id) %>
            </em>
          </footer>
        </blockquote>
    <% end %>

  </div>
</div>

app/views/questionnaire/reports/show.html.erb
<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <h3>
      <%= @title = t '.title', title: @report.title %>
      <% if current_user && current_user.is_admin? %>
          <%= render 'shared/button', title: :show, href: questionnaire_report_result_path(@report), sm: true %>
          <%= render 'shared/button', title: :edit, href: edit_questionnaire_report_path(@report), sm: true %>
      <% end %>
    </h3>
    <hr/>
    <p>
      <%= raw to_html(@report.summary) %>
    </p>
    <%= form_tag questionnaire_report_answer_path(@report) do |q| %>
        <% @report.questions.order(id: :asc).each do |q| %>
            <% id = "f_#{q.id}" %>
            <div class="form-group">
              <%= label_tag id, q.name %>
              <% case %>
              <% when q.y_n? %>
                  <label>
                    <input type="radio" name="<%= id %>" value="<%= t 'buttons.y' %>">
                    <%= t 'buttons.y' %>
                  </label>
                  <label>
                    <input type="radio" name="<%= id %>" value="<%= t 'buttons.y' %>">
                    <%= t 'buttons.n' %>
                  </label>
              <% when q.single? %>
                  <%= text_field_tag id, '', class: 'form-control' %>
              <% when q.multi? %>
                  <%= text_area_tag id, '', class: 'form-control' %>
              <% else %>
              <% end %>
            </div>
        <% end %>

        <p>
          <%= render 'shared/recaptcha' %>
        </p>
        <%= submit_tag t('buttons.submit'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>