config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :attachments, except: [:update, :edit, :new, :show]

  namespace :cms do
    resources :users, only:[:show, :index]
    resources :tags
    resources :articles do
      post :top
    end
    resources :comments, except: [:new, :show]
  end

  resources :notices, only: [:index, :create, :destroy]

  %w(info seo captcha adverts users about_us map).each do |a|
    get "site/#{a}"
    post "site/#{a}"
  end
  put 'site/role'
  get 'site/status'
  get 'site' => 'site#index'

  get 'ueditor' =>'ueditor#index'
  post 'ueditor' =>'ueditor#index'

  get 'personal/logs'

  resources :books, only: [:index, :show]

  get 'about_us' => 'home#about_us'
  get 'search' => 'home#search'
  get 'rss.atom' => 'home#rss', format: false, as: :rss
  get 'robots.txt' => 'home#robots', format: false, as: :robots
  get 'baidu_verify_(*id)', to: 'home#baidu', as: :baidu, format: true, constraints: {format: :html}
  get 'google(*id)', to: 'home#google', as: :google, format: true, constraints: {format: :html}

  namespace :questionnaire do
    resources :answers, only: [:destroy]
    resources :questions, except: [:index, :show]
    resources :reports do
      post :answer
      get :result
    end
  end

  resources :friend_links, only:[:index, :create, :destroy]
  resources :leave_words, only:[:index, :create, :destroy]
  get 'utils' =>'utils#index'

  devise_for :users

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'

end

app/views/shared/_ajax_button.html.erb
<% case title %>
<% when :remove %>
    <%= button_tag t('buttons.remove'), id: "#{id}-remove-#{href}", class: "btn btn-danger #{'btn-sm' if sm}" %>
<% else %>
    <%= button_tag t('buttons.submit'), id: "#{id}-view-#{href}", class: "btn btn-primary #{'btn-sm' if sm}" %>
<% end %>

app/views/shared/_button.html.erb
<% case title %>
<% when :remove %>
    <%= link_to t('buttons.remove'), href, class: "btn btn-danger #{'btn-sm' if sm}", method: :delete, data: {confirm: t('messages.are_you_sure')} %>
<% when :show %>
    <%= link_to t('buttons.view'), href, class: "btn btn-secondary #{'btn-sm' if sm}" %>
<% when :new %>
    <%= link_to t('buttons.new'), href, class: "btn btn-success #{'btn-sm' if sm}" %>
<% when :edit %>
    <%= link_to t('buttons.edit'), href, class: "btn btn-warning #{'btn-sm' if sm}" %>
<% else %>
    <%= link_to t('buttons.submit'), href, class: "btn btn-primary #{'btn-sm' if sm}" %>
<% end %>

app/views/shared/_footer.html.erb
<% cache "footer/#{I18n.locale}" do %>
    <hr/>
    <div class="row">
      <% FriendLink.select(:home, :name, :logo).each do |fl| %>
          <div class="col-sm-1">
            <%= link_to (fl.logo && !fl.logo.empty? ? image_tag(fl.logo, alt: fl.name, class: 'fill-div') : fl.name), fl.home, target: '_blank' %>
          </div>
      <% end %>
    </div>
    <hr/>
    <footer>
      <p class="pull-right">
        <%= link_to image_tag('famfamfam-flags/dist/png/cn.png'), url_for(locale: 'zh-CN'), target: '_blank' %>
        &nbsp;
        <%= link_to image_tag('famfamfam-flags/dist/png/us.png'), url_for(locale: 'en'), target: '_blank' %>
        &nbsp;
        <%= link_to image_tag('famfamfam-silk/dist/png/rss.png'), rss_path, target: '_blank' %>
        &nbsp;
        <%= link_to t('links.back_to_top'), request.fullpath %>
      </p>

      <p>
        <%= raw t('links.build_by_html', version: current_version) %>
        &nbsp;
        <%= "#{t 'simple_form.labels.about_us.address'}: #{Setting.site_address}" %>
        &nbsp;
        <%= Setting.get_site_info 'copyright' %>
      </p>
    </footer>
<% end %>

app/views/shared/_header.html.erb
<style>
  body {
    margin-top: 70px;
  }
</style>

<nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
  <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#top-nav-bar">
    &#9776;
  </button>
  <div class="collapse navbar-toggleable-sm" id="top-nav-bar">
    <%= link_to Setting.get_site_info('title')||'', root_path, class: 'navbar-brand' %>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <%= link_to t('cms.articles.index.title'), cms_articles_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('cms.users.index.title'), cms_users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('home.search.title.index'), search_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('site.about_us.title'), about_us_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if I18n.locale==:en %>">
        <%= link_to 'English', root_path(locale: 'en'), class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if I18n.locale=='zh-CN'.to_sym %>">
        <%= link_to '简体中文', root_path(locale: 'zh-CN'), class: 'nav-link' %>
      </li>
    </ul>
    <ul class="nav navbar-nav pull-right">
      <li class="nav-item">
        <%= form_tag search_path, method: :get, class: 'form-inline navbar-form' do %>
            <%= text_field_tag :keyword, '', class: 'form-control', placeholder: t('placeholders.search') %>
            <%= submit_tag t('buttons.search'), class: 'btn btn-success-outline' %>
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="sign-in-or-up" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= user_signed_in? ? t('links.welcome', name: current_user.username) : t('links.sign_in_or_up') %>
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="sign-in-or-up">
          <% if user_signed_in? %>
              <%= link_to t('cms.articles.new.title'), new_cms_article_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to t('personal.index.title'), personal_logs_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to t('links.sign_out'), destroy_user_session_path, class: 'dropdown-item' %>
          <% else %>
              <%= link_to t('devise.shared.links.sign_in'), new_user_session_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to t('devise.shared.links.sign_up'), new_user_registration_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to t('devise.shared.links.forgot_your_password'), new_user_password_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to t('devise.shared.links.didn_t_receive_confirmation_instructions'), new_user_confirmation_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to t('devise.shared.links.didn_t_receive_unlock_instructions'), new_user_unlock_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_manage_column.html.erb
<%= render 'shared/button', title: :edit, href: edit, sm: true %>
<%= render 'shared/button', title: :remove, href: remove, sm: true %>

app/views/shared/_messages.html.erb
<% if notice %>
    <div class="alert alert-info alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <strong><%= notice %></strong>
    </div>
<% end %>

<% if alert %>
    <div class="alert alert-warning alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <strong><%= alert %></strong>
    </div>
<% end %>

app/views/shared/_recaptcha.html.erb
<div class="g-recaptcha" data-sitekey="<%= Setting.recaptcha_site_key %>"></div>

app/views/shared/_tab_h.html.erb
<% tid = "tab-h-#{id}-tabs" %>
<% cid = "tab-h-#{id}-content" %>
<ul id="<%= tid %>" class="nav nav-tabs">
  <% links.each do |l| %>
      <li class="nav-item">
        <%= link_to t(l.fetch(:title)), '#', class: 'nav-link', id: l.fetch(:href) %>
      </li>
  <% end %>
</ul>
<br/>
<div id="<%= cid %>"></div>
<script>
  $(function () {
    var ids = "ul#<%= tid %> a";
    $(ids).click(function (e) {
      e.preventDefault();
      $.get($(this).attr('id'), function (data) {
        $("div#<%= cid %>").html(data);
      });
      $(this).tab('show');
    });
  });
</script>

app/views/shared/_tab_v.html.erb
<% id = "tab-v-#{id}-tabs" %>
<ul id="<%= id %>" class="nav nav-pills nav-stacked">
  <% links.each do |l| %>
      <li class="nav-item">
        <%= link_to t(l.fetch(:title)), l.fetch(:href), class: 'nav-link' %>
      </li>
  <% end %>
</ul>
<script>
  $(function () {
    var url = location.pathname + "?";
    $("ul#<%= id %> a").each(function () {
      if ($(this).attr('href').substring(0, url.length) == url) {
        $(this).tab('show');
      }
    });
  });
</script>

app/views/shared/_ueditor.html.erb
<p>

  <script type="text/plain" name="<%= id %>" id="<%= id %>-container">
    <%= raw content %>
  </script>

  <script type="text/javascript">
    <% ue_id = "ue#{SecureRandom.hex}" %>
    var <%= ue_id%> =
    UE.getEditor('<%= id %>-container');
    <%= ue_id%>.ready(function () {
      <%= ue_id%>.
      execCommand('serverparam', {
        'authenticity_token': '<%= form_authenticity_token %>',
        'key2': 'value2'
      });
    });
  </script>
</p>