config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :attachments, except: [:update, :edit, :new, :show]

  namespace :cms do
    resources :users, only:[:show, :index]
    resources :tags
    resources :articles do
      post :top
    end
    resources :comments, except: [:new, :show]
  end

  resources :notices, only: [:index, :create, :destroy]

  %w(info seo captcha adverts users about_us map).each do |a|
    get "site/#{a}"
    post "site/#{a}"
  end
  put 'site/role'
  get 'site/status'
  get 'site' => 'site#index'

  get 'ueditor' =>'ueditor#index'
  post 'ueditor' =>'ueditor#index'

  get 'personal/logs'

  resources :books, only: [:index, :show]

  get 'about_us' => 'home#about_us'
  get 'search' => 'home#search'
  get 'rss.atom' => 'home#rss', format: false, as: :rss
  get 'robots.txt' => 'home#robots', format: false, as: :robots
  get 'baidu_verify_(*id)', to: 'home#baidu', as: :baidu, format: true, constraints: {format: :html}
  get 'google(*id)', to: 'home#google', as: :google, format: true, constraints: {format: :html}

  namespace :questionnaire do
    resources :answers, only: [:destroy]
    resources :questions, except: [:index, :show]
    resources :reports do
      post :answer
      get :result
    end
  end

  resources :friend_links, only:[:index, :create, :destroy]
  resources :leave_words, only:[:index, :create, :destroy]
  get 'utils' =>'utils#index'

  devise_for :users

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'

end

app/controllers/home_controller.rb
require 'rss'
require 'portal/book'

class HomeController < ApplicationController
  def index
    @hot = Cms::Article.select(:id, :title, :summary, :logo).where(lang: I18n.locale).order(visits: :desc).limit(8).select { |a| a.logo }
    @top = Cms::Article.select(:id, :title, :summary, :logo).where(top: true)
    @users = User.select(:id, :username, :details, :logo).order(sign_in_count: :desc).limit(4).select { |u| !u.is_admin? }
    @books = Portal::Book.names.sample 6
    @notices = Notice.select(:content, :created_at).where(lang: I18n.locale).order(id: :desc).limit(6)
    render layout: 'cms'
  end

  def about_us
    @key = Setting.google_map_browser_key
    @loc = Setting.site_geometry
    @place_id = Setting.site_place_id
    @leave_word = LeaveWord.new
    render layout: 'cms'
  end

  def search
    @keyword = params[:@keyword]
    @id = Setting.google_search_id
    render layout: 'cms'
  end

  def rss
    locale = I18n.locale
    xml = Rails.cache.fetch("cache://#{locale}/rss.atom", expires_in: 8.hours) do
      rss = RSS::Maker.make('atom') do |maker|
        maker.channel.author = Setting.site_author
        maker.channel.updated = Time.now.to_s
        maker.channel.about = rss_url
        maker.channel.title = Setting.get_site_info 'title'

        Cms::Article.select(:id, :title, :updated_at).where(lang: locale).order(id: :desc).limit(120).each do |a|
          maker.items.new_item do |item|
            item.link = cms_articles_url(id: a.id)

            item.title = a.title
            item.updated = a.updated_at.utc
          end
        end
      end
      rss.to_s
    end

    render xml: xml
  end

  def baidu
    code = Setting.baidu_site_id
    if code == params.fetch(:id)
      render text: code
    else
      head :not_found
    end
  end

  def google
    code = Setting.google_site_id
    if code == params.fetch(:id)
      render text: "google-site-verification: google#{code}.html"
    else
      head :not_found
    end

  end

  def robots
    render plain: Setting.robots_txt
  end
end

app/views/home/about_us.html.erb
<% @title = t 'site.about_us.title' %>
<style type="text/css">
  #map {
    height: 100%;
  }

  html, body {
    height: 100%;
  }

</style>

<div class="row">
  <div class="col-sm-offset-1 col-sm-10">
    <div>
      <%= raw to_html(Setting.get_site_info('details')) %>
    </div>

    <% if @place_id && @key %>
        <iframe width="600" height="450" frameborder="0" style="border:0"
                src="https://www.google.com/maps/embed/v1/place?q=place_id:<%= @place_id %>&key=<%= @key %>" allowfullscreen>
        </iframe>
    <% end %>

    <br/>
    <h4><%= t '.leave_message' %></h4>
    <hr>
    <%= simple_form_for(@leave_word) do |f| %>
        <%= f.input :content, as: :text %>
        <%= f.button :submit, t('buttons.submit') %>
    <% end %>

  </div>
</div>

app/views/home/about_us_1.html.erb
<% @title = t 'site.about_us.title' %>
<style type="text/css">
  #map {
    height: 100%;
  }

  html, body {
    height: 100%;
  }

</style>

<div class="row">
  <div class="col-sm-offset-1 col-sm-10">
    <div>
      <%= raw to_html(Setting.get_site_info('details')) %>
    </div>

    <div id="map"></div>

    <br/>
    <h4><%= t '.leave_message' %></h4>
    <hr>
    <%= simple_form_for(@leave_word) do |f| %>
        <%= f.input :content, as: :text %>
        <%= f.button :submit, t('buttons.submit') %>
    <% end %>

  </div>
</div>

<% if @loc && @key %>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: <%= @loc.fetch :lat %>, lng: <%= @loc.fetch :lng%>},
          zoom: 8
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= @key %>&callback=initMap"
            async defer></script>
<% end %>

app/views/home/index.html.erb
<% @title = t '.title' %>
<style>
  body {
    margin-top: 50px;
  }
</style>
<div class="row">
  <div id="carousel-top-article" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <% @top.each_index do |i| %>
          <li data-target="#carousel-example-generic" data-slide-to="<%= i %>" class="<%= 'active' if i == 0 %>"></li>
      <% end %>
    </ol>
    <div class="carousel-inner" role="listbox">
      <% @top.each_with_index do |a, i| %>
          <div class="carousel-item <%= 'active' if i == 0 %>">
            <img class="fill-div" src="<%= a.logo %>" alt="<%= a.title %>">

            <div class="carousel-caption">
              <h3><%= a.title %></h3>

              <p><%= a.summary %></p>

              <p>
                <%= link_to t('buttons.view'), cms_article_path(a), class: 'btn btn-primary', target: '_blank' %>
              </p>
            </div>
          </div>
      <% end %>
    </div>
    <a class="left carousel-control" href="#carousel-top-article" role="button" data-slide="prev">
      <span class="icon-prev" aria-hidden="true"></span>
      <span class="sr-only"><%= t 'buttons.previous' %></span>
    </a>
    <a class="right carousel-control" href="#carousel-top-article" role="button" data-slide="next">
      <span class="icon-next" aria-hidden="true"></span>
      <span class="sr-only"><%= t 'buttons.next' %></span>
    </a>
  </div>
</div>
<br/>

<div class="row">
  <% @notices.each do |n| %>
      <div class="col-md-2">
        <blockquote class="blockquote">
          <p><%= raw to_html(n.content)%></p>
          <footer><%= time_ago_in_words n.created_at %></footer>
        </blockquote>
      </div>
  <% end %>
</div>


<hr/>
<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <div class="row">
      <% @users.each do |u| %>
          <div class="col-md-3">
            <img class="img-circle" src="<%= u.logo %>"/>

            <h2><%= u.username %></h2>

            <p>
              <%= u.details %>
            </p>

            <p>
              <%= link_to t('buttons.view'), cms_user_path(u), class: 'btn btn-secondary', target: '_blank' %>
            </p>
          </div>
      <% end %>
    </div>
  </div>
</div>

<% @hot.each_with_index do |a, i| %>

    <hr/>
    <% if i.odd? %>
        <div class="row">
          <div class="col-md-7 col-md-offset-1">

            <h2><%= a.title %></h2>

            <p><%= a.summary %></p>

            <p>
              <%= link_to t('buttons.view'), cms_article_path(a), class: 'btn btn-secondary', target: '_blank' %>
            </p>
          </div>
          <div class="col-md-3">
            <a href="<%= cms_article_path(a) %>" target="_blank">
              <img class="fill-div" src="<%= a.logo %>">
            </a>
          </div>
        </div>
    <% else %>
        <div class="row">
          <div class="col-md-3 col-md-offset-1">
            <a href="<%= cms_article_path(a) %>" target="_blank">
              <img class="fill-div" src="<%= a.logo %>">
            </a>
          </div>
          <div class="col-md-7">

            <h2><%= a.title %></h2>

            <p><%= a.summary %></p>

            <p>
              <%= link_to t('buttons.view'), cms_article_path(a), class: 'btn btn-secondary', target: '_blank' %>
            </p>
          </div>
        </div>
    <% end %>
<% end %>

<% cache "books/sample/#{I18n.locale}" do %>
    <hr/>
    <div class="row">
      <% @books.each do |b| %>
          <div class="col-sm-2">
            <div class="card card-block">
              <h4 class="card-title"><%= b %></h4>
              <%= link_to t('buttons.view'), book_path(b), class: 'card-link' %>
            </div>
          </div>
      <% end %>
    </div>
<% end %>

app/views/home/search.html.erb
<% @title = t '.title.results', keyword: params[:keyword] %>

<div class="row">
  <div class="col-sm-offset-1 col-sm-10">
    <% if @id %>
        <script>
          (function () {
            var cx = '<%= @id%>';
            var gcse = document.createElement('script');
            gcse.type = 'text/javascript';
            gcse.async = true;
            gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
                '//cse.google.com/cse.js?cx=' + cx;
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(gcse, s);
          })();
        </script>
        <gcse:search></gcse:search>
    <% end %>
  </div>
</div>