config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :attachments, except: [:update, :edit, :new, :show]

  namespace :cms do
    resources :users, only:[:show, :index]
    resources :tags
    resources :articles do
      post :top
    end
    resources :comments, except: [:new, :show]
  end

  resources :notices, only: [:index, :create, :destroy]

  %w(info seo captcha adverts users about_us map).each do |a|
    get "site/#{a}"
    post "site/#{a}"
  end
  put 'site/role'
  get 'site/status'
  get 'site' => 'site#index'

  get 'ueditor' =>'ueditor#index'
  post 'ueditor' =>'ueditor#index'

  get 'personal/logs'

  resources :books, only: [:index, :show]

  get 'about_us' => 'home#about_us'
  get 'search' => 'home#search'
  get 'rss.atom' => 'home#rss', format: false, as: :rss
  get 'robots.txt' => 'home#robots', format: false, as: :robots
  get 'baidu_verify_(*id)', to: 'home#baidu', as: :baidu, format: true, constraints: {format: :html}
  get 'google(*id)', to: 'home#google', as: :google, format: true, constraints: {format: :html}

  namespace :questionnaire do
    resources :answers, only: [:destroy]
    resources :questions, except: [:index, :show]
    resources :reports do
      post :answer
      get :result
    end
  end

  resources :friend_links, only:[:index, :create, :destroy]
  resources :leave_words, only:[:index, :create, :destroy]
  get 'utils' =>'utils#index'

  devise_for :users

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'

end

app/controllers/site_controller.rb
require 'etc'

class SiteController < ApplicationController
  before_action :must_be_admin!

  layout false

  def about_us
    case request.method
      when 'POST'
        si = params.require('about_us').permit(:details, :address)
        address = si.fetch :address
        key = Setting.google_map_server_key
        if key
          uri = URI 'https://maps.googleapis.com/maps/api/geocode/json'
          uri.query = URI.encode_www_form key: key, address: address
          res = Net::HTTP.get_response uri
          unless res.is_a?(Net::HTTPSuccess)
            render(json: {ok: false}) and return
          end
          map = JSON.parse res.body
          unless map['status'] == 'OK'
            render(json: {ok: false, data: map['status']}) and return
          end
          mrs = map['results'].first
          address = mrs['formatted_address']
          Setting.site_geometry = {lat: mrs['geometry']['location']['lat'], lng: mrs['geometry']['location']['lng']}
          Setting.site_place_id = mrs['place_id']
        end

        Setting[_s_key('details')] = si.fetch :details
        Setting.site_address = address
        render json: {ok: true}
      else
    end
  end

  def info

    case request.method
      when 'POST'
        si = params.require('site').permit(:favicon, :title, :keywords, :description, :author, :copyright)
        Setting[_s_key('title')] = si.fetch :title
        Setting[_s_key('keywords')] = si.fetch :keywords
        Setting[_s_key('description')] = si.fetch :description
        Setting[_s_key('copyright')] = si.fetch :copyright
        Setting.site_author = si.fetch :author
        Setting.site_favicon = si.fetch :favicon
        render json: {ok: true}
      else
    end
  end

  def captcha
    case request.method
      when 'POST'
        si = params.require('captcha').permit(:site_key, :secret_key)
        Setting.recaptcha_site_key = si.fetch :site_key
        Setting.recaptcha_secret_key = si.fetch :secret_key
        render json: {ok: true}
      else
    end
  end

  def seo
    case request.method
      when 'POST'
        si = params.require('seo').permit(:google_tracking_id, :google_search_id, :google_site_id, :baidu_site_id, :robots_txt)
        Setting.google_search_id = si.fetch :google_search_id
        Setting.google_tracking_id = si.fetch :google_tracking_id
        Setting.google_site_id = si.fetch :google_site_id
        Setting.baidu_site_id = si.fetch :baidu_site_id
        Setting.robots_txt = si.fetch :robots_txt
        render json: {ok: true}
      else
    end
  end

  def map
    case request.method
      when 'POST'
        si = params.require('map').permit(:server_key, :browser_key)
        Setting.google_map_server_key = si.fetch :server_key
        Setting.google_map_browser_key = si.fetch :browser_key
        render json: {ok: true}
      else
    end
  end

  def status
    @system = {
        user: ENV['USER'],
        time: Time.now,
        os: Etc.uname,
        ruby: {
            version: "#{RUBY_VERSION}(#{RUBY_RELEASE_DATE})",
            bin: `which ruby`.chomp,
        },
        rails: {
            env: Rails.env,
            version: Rails.version,
            root: Rails.root,
        }
    }

    @redis = Rails.application.config.redis.info

    conn = ActiveRecord::Base.connection
    cfg = Rails.configuration.database_configuration[Rails.env]
    @database = {
        size: conn.exec_query("select pg_size_pretty(pg_database_size('#{cfg['database']}'))").first['pg_size_pretty'],
        activity: conn.exec_query('SELECT pid,waiting,current_timestamp - least(query_start,xact_start) AS runtime, substr(query,1,32) AS current_query FROM pg_stat_activity WHERE NOT pid=pg_backend_pid()').map { |row|
          {pid: row['pid'], waiting: row['waiting'], runtime: row['runtime'], current_query: row['current_query']}
        },
    }
  end

  def adverts
    case request.method
      when 'POST'
        si = params.require('adverts').permit(:vertical, :horizontal)
        Setting.advert_horizontal = si.fetch :horizontal
        Setting.advert_vertical = si.fetch :vertical
        render json: {ok: true}
      else
    end
  end

  def users
    @users = initialize_grid(User.select(:id, :username, :email, :last_sign_in_at, :sign_in_count, :created_at).order(sign_in_count: :desc, id: :desc))
    render layout: 'personal'
  end

  def role
    user = User.find params[:user]
    role = params[:role]
    apply = params[:apply] == 'true'
    if user && user.confirmed? && !user.is_root?
      case role
        when 'admin'
          if apply
            user.add_role role
          else
            user.remove_role role
          end
          flash[:notice] = t 'messages.success'
        else
          flash[:alert] = t 'messages.failed'
      end
    else
      flash[:alert] = t 'messages.failed'

    end
    redirect_to site_users_path
  end

  def index
    @links = [
        {href: leave_words_path, title: 'site.index.leave_words'},
        {href: site_info_path, title: 'site.index.info'},
        {href: site_about_us_path, title: 'site.about_us.title'},
        {href: site_captcha_path, title: 'site.index.captcha'},
        {href: site_seo_path, title: 'site.index.seo'},
        {href: site_status_path, title: 'site.index.status'},
        {href: site_adverts_path, title: 'site.index.adverts'},
        {href: site_map_path, title: 'site.index.map'},
        {href: notices_path, title: 'notices.index.title'},
        {href: friend_links_path, title: 'friend_links.index.title'},
    ]
    render layout: 'personal'
  end

  private
  def _s_key(k)
    "#{I18n.locale}://site/#{k}"
  end
end

app/views/site/about_us.html.erb
<div id="about_us-msg"></div>
<%= simple_form_for 'about_us', html: {id: 'about_us'} do |f| %>
    <%= f.input :address, input_html: {value: Setting.site_address} %>
    <%= f.input :details, as: :text, input_html: {value: Setting.get_site_info('details')} %>
    <%= f.button :submit, t('buttons.submit') %>
<% end %>

<script>
  $(function () {
    submit_form('about_us');
  });
</script>

app/views/site/adverts.html.erb
<div id="adverts-msg"></div>
<%= simple_form_for 'adverts', html: {id: 'adverts'} do |f| %>
    <%= f.input :vertical, as: :text, autofocus: true, input_html: {value: Setting.advert_vertical} %>
    <%= f.input :horizontal, as: :text, input_html: {value: Setting.advert_horizontal} %>
    <%= f.button :submit, t('buttons.submit') %>
<% end %>

<br/>
<h3><%= t 'simple_form.labels.adverts.vertical' %></h3>
<hr/>
<%= raw Setting.advert_vertical %>
<h3><%= t 'simple_form.labels.adverts.horizontal' %></h3>
<hr/>
<%= raw Setting.advert_horizontal %>

<script>
  $(function () {
    submit_form('adverts');
  });
</script>

app/views/site/captcha.html.erb
<div id="captcha-msg"></div>
<%= simple_form_for 'captcha', html: {id: 'captcha'} do |f| %>
    <h3>reCaptcha</h3>
    <hr/>
    <%= f.input :site_key, autofocus: true, input_html: {value: Setting.recaptcha_site_key} %>
    <%= f.input :secret_key, input_html: {value: Setting.recaptcha_secret_key} %>
    <%= f.button :submit, t('buttons.submit') %>
<% end %>

<script>
  $(function () {
    submit_form('captcha');
  });
</script>

app/views/site/index.html.erb
<% @title = t '.title' %>
<%= render 'shared/tab_h', id: 'site', links: @links %>

app/views/site/info.html.erb
<div id="site-msg"></div>
<%= simple_form_for 'site', html: {id: 'site'} do |f| %>
    <%= f.input :favicon, autofocus: true, input_html: {value: Setting.site_favicon} %>
    <%= f.input :title, input_html: {value: Setting.get_site_info('title')} %>
    <%= f.input :keywords, input_html: {value: Setting.get_site_info('keywords')} %>
    <%= f.input :author, input_html: {value: Setting.site_author} %>
    <%= f.input :description, as: :text, input_html: {value: Setting.get_site_info('description')} %>
    <%= f.input :copyright, input_html: {value: Setting.get_site_info('copyright')} %>
    <%= f.button :submit, t('buttons.submit') %>
<% end %>

<script>
  $(function () {
    submit_form('site');
  });
</script>

app/views/site/map.html.erb
<div id="map-msg"></div>
<%= simple_form_for 'map', html: {id: 'map'} do |f| %>

    <%= f.input :server_key, autofocus: true, input_html: {value: Setting.google_map_server_key} %>
    <%= f.input :browser_key, autofocus: true, input_html: {value: Setting.google_map_browser_key} %>

    <%= f.button :submit, t('buttons.submit') %>
<% end %>
<script>
  $(function () {
    submit_form('map');
  });
</script>

app/views/site/seo.html.erb
<div id="seo-msg"></div>
<%= simple_form_for 'seo', html: {id: 'seo'} do |f| %>
    <%= f.input :google_search_id, autofocus: true, input_html: {value: Setting.google_search_id} %>
    <%= f.input :google_tracking_id, input_html: {value: Setting.google_tracking_id} %>
    <%= f.input :google_site_id, input_html: {value: Setting.google_site_id} %>
    <br/>
    <%= f.input :baidu_site_id, input_html: {value: Setting.baidu_site_id} %>
    <br/>
    <%= f.input :robots_txt, as: :text, input_html: {value: Setting.robots_txt} %>
    <%= f.button :submit, t('buttons.submit') %>
<% end %>
<br/>
<div class="btn-group btn-group-lg" role="group">
  <%= link_to 'Google', google_path(id: Setting.google_site_id, format: :html, locale: nil), class: 'btn btn-default', target: '_blank' %>
  <%= link_to 'Baidu', baidu_path(id: Setting.baidu_site_id, format: :html, locale: nil), class: 'btn btn-default', target: '_blank' %>
  <%= link_to 'robots.txt', robots_path(locale: nil), class: 'btn btn-default', target: '_blank' %>
</div>
<script>
  $(function () {
    submit_form('seo');
  });
</script>

app/views/site/status.html.erb
<div class="row">
  <div class="col-sm-6">
    <h4><%= t '.system' %></h4>
    <hr/>
    <pre>
      <code class="json"><%= to_json(@system) %></code>
    </pre>
  </div>
  <div class="col-sm-6">
    <h4>
      <%= t '.jobs' %>(
      <%= link_to t('.details'), sidekiq_web_path(locale: nil), target: '_blank', class: 'btn btn-success' %>
      )
    </h4>
    <hr/>
    <pre>
      <code class="json" id="cd-jobs"></code>
    </pre>
  </div>
  <div class="col-sm-6">
    <h4>Redis</h4>
    <hr/>
    <pre>
      <code class="json"><%= to_json(@redis) %></code>
    </pre>
  </div>
  <div class="col-sm-6">
    <h4><%= t '.database' %></h4>
    <hr/>
    <pre>
      <code class="json"><%= to_json(@database) %></code>
    </pre>
  </div>
</div>


<script>
  $(function () {
    $.get('/sidekiq/stats', function (rs) {
      $("code#cd-jobs").text(to_json(rs));
      show_code();
    });
  });
</script>

app/views/site/users.html.erb
<% @title = t '.title' %>
<%= grid(@users) do |g|

  g.column name: 'ID' do |u|
    u.id
  end
  g.column name: t('.name') do |u|
    "#{u.username}<#{u.email}>"
  end
  g.column name: t('.last_sign_in') do |u|
    "#{u.last_sign_in_at ? time_ago_in_words(u.last_sign_in_at) : '-'}(#{u.sign_in_count})"
  end
  g.column name: t('.role') do |u|
    unless u.is_root?
      u.is_admin? ?
          button_to(t('.remove_admin'), site_role_path(role: 'admin', user: u.id, apply: false), method: :put, class: 'btn btn-sm btn-info', data: {confirm: t('messages.are_you_sure')}) :
          button_to(t('.add_admin'), site_role_path(role: 'admin', user: u.id, apply: true), method: :put, class: 'btn btn-sm btn-danger', data: {confirm: t('messages.are_you_sure')})
    end
  end
  g.column name: t('.created_at') do |u|
    time_ago_in_words u.created_at
  end
end -%>